projects:
  bazaar:
    schemaPath: utils/graphql/schema.json
    includes:
      - utils/graphql/*.js
    excludes:
      - ./amplify/**
    extensions:
      amplify:
        codeGenTarget: javascript
        generatedFileName: ''
        docsFilePath: utils/graphql
extensions:
  amplify:
    version: 3
